[package]
name = "zensloom-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.23", features = ["derive"] }
zensloom-utils = { path = "../../crates/utils" }
zensloom-project = { path = "../../crates/project" }
zensloom-rendering = { path = "../../crates/rendering" }
zensloom-editor = { path = "../../crates/editor" }
zensloom-media = { path = "../../crates/media" }
zensloom-flags = { path = "../../crates/flags" }
zensloom-recording = { path = "../../crates/recording" }
zensloom-export = { path = "../../crates/export" }
zensloom-camera = { path = "../../crates/camera" }
scap-targets = { path = "../../crates/scap-targets" }
serde = { workspace = true }
serde_json = "1.0.133"
tokio.workspace = true
uuid = { version = "1.11.1", features = ["v4"] }
ffmpeg = { workspace = true }
tracing.workspace = true
tracing-subscriber = "0.3.19"
flume.workspace = true
workspace-hack = { version = "0.1", path = "../../crates/workspace-hack" }

[target.'cfg(target_os = "macos")'.dependencies]
cidre = { workspace = true }

[lints]
workspace = true
