name: CI
on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

jobs:
  lint-format:
    name: Lint & Format
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
      - uses: biomejs/setup-biome@v2
        with:
          version: 2.2.0
      - run: biome ci .

  clippy:
    name: Clippy & Rustfmt
    runs-on: windows-2022
    env:
      LIBCLANG_PATH: "C:/Program Files/LLVM/bin"
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@1.88.0
        with:
          targets: x86_64-pc-windows-msvc
          components: clippy, rustfmt
      - uses: KyleMayes/install-llvm-action@v2
        with:
          version: "18.1"
      - uses: Swatinem/rust-cache@v2
      - run: cargo fmt --check
      - run: node scripts/setup.js
      - run: cargo clippy --workspace --locked -- -D warnings

  build:
    name: Build Desktop
    runs-on: windows-2022
    needs: [clippy]
    env:
      LIBCLANG_PATH: "C:/Program Files/LLVM/bin"
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@1.88.0
        with:
          targets: x86_64-pc-windows-msvc
      - uses: KyleMayes/install-llvm-action@v2
        with:
          version: "18.1"
      - uses: Swatinem/rust-cache@v2
      - uses: actions/setup-node@v4
        with:
          node-version: 24
      - uses: pnpm/action-setup@v4
        with:
          version: 10
      - run: pnpm install --frozen-lockfile
      - run: node scripts/setup.js
      - run: cargo check --workspace
